services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  influxdb:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

  telegraf:
    image: telegraf
    container_name: telegraf
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  collector:
    build: .
    container_name: collector
    depends_on:
      - mosquitto
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
    volumes:
      - .:/app
volumes:
  influxdb-data:
  grafana-data: