[pytest]
testpaths = test/unit/src
pythonpath = src
addopts = --strict-markers --cov=src --cov-branch --cov-report=term-missing --cov-report=html:coverage_html --cov-report=xml:coverage.xml
env =
	PYTHONPATH=src
